version: 2
updates:
  - package-ecosystem: uv
    directory: /python
    schedule:
      interval: weekly
    groups:
      python-tooling:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ['*']
