python := if os() == "windows" { "python" } else { "python3" }

default: check

check:
    {{python}} scripts/check.py check

format:
    {{python}} scripts/check.py format

sync:
    {{python}} scripts/check.py sync

lock:
    {{python}} scripts/check.py lock

build:
    {{python}} scripts/check.py build

check-package:
    {{python}} scripts/check.py check-package

audit-dependencies:
    {{python}} scripts/check.py audit-dependencies

check-workflow:
    {{python}} scripts/check.py check-workflow
